name: On PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraformsentinalcheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Infra Deployment Started
        run: |
          echo "Job started"
          echo "test 1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Set Terraform workspace
        run: echo -e "terraform {\n  backend \"remote\" {\n    organization = \"${{ vars.ORGANIZATION}}\"\n\n    workspaces {\n      name = \"${{ vars.WORKSPACE}}\"\n    }\n  }\n}" > workspace.tf

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init